### ISSUE TITLE
error in layer_output? 

### ISSUE THREAD

**Issue by Peyton-D** [beatLaboratory/TIMBRE#1]
Greetings,
I tried to run the toy_data_demo in jupyter notebook but encountered the following error:

ValueError                                Traceback (most recent call last)
Cell In[11], line 6
      4 X = np.concatenate((np.real(data), np.imag(data)), axis=1)  # preprocess
      5 for i in range(len(m.layers)):  # plot the output of each layer in network
----> 6     pr = layer_output(data, m, i)
      7     for j in range(pr.shape[1]):
      8         axs1[i].plot(pr[:, j], styles[j]);

File ~\Downloads\TIMBRE\helpers.py:116, in layer_output(X, m, layer_num)
    114 # stack the real and imaginary components of the data
    115 X = np.concatenate((np.real(X), np.imag(X)), axis=1)
--> 116 m1 = models.Model(inputs=m.input, outputs=m.layers[layer_num].output)
    117 return m1.predict(X)

File ~\miniconda3\Lib\site-packages\keras\src\ops\operation.py:228, in Operation.input(self)
    218 @property
    219 def input(self):
    220     """Retrieves the input tensor(s) of a symbolic operation.
    221 
    222     Only returns the tensor(s) corresponding to the *first time*
   (...)
    226         Input tensor or list of input tensors.
    227     """
--> 228     return self._get_node_attribute_at_index(0, "input_tensors", "input")

File ~\miniconda3\Lib\site-packages\keras\src\ops\operation.py:259, in Operation._get_node_attribute_at_index(self, node_index, attr, attr_name)
    243 """Private utility to retrieves an attribute (e.g. inputs) from a node.
    244 
    245 This is used to implement the properties:
   (...)
    256     The operation's attribute `attr` at the node of index `node_index`.
    257 """
    258 if not self._inbound_nodes:
--> 259     raise ValueError(
    260         f"The layer {self.name} has never been called "
    261         f"and thus has no defined {attr_name}."
    262     )
    263 if not len(self._inbound_nodes) > node_index:
    264     raise ValueError(
    265         f"Asked to get {attr_name} at node "
    266         f"{node_index}, but the operation has only "
    267         f"{len(self._inbound_nodes)} inbound nodes."
    268     )

ValueError: The layer sequential has never been called and thus has no defined input.

I also encountered this same error when trying to run TIMBRE on my own data in a separate notebook.

**Comment by synapticleft** [comment]
Thanks for the issue, we have confirmed that we get this error when using something other than Colab and are looking into it. In the meantime, one option might be to use Colab locally on your machine (by clicking the 'connect' tab in the upper right and choosing 'connect to a local runtime').

**Comment by synapticleft** [comment]
I updated helpers.py and the problem appears to be fixed in jupyter now - could you confirm?

**Comment by Peyton-D** [comment]
Yes, it works for me now. Thanks!
